#!/bin/sh
# Query the cli call collcetion
#
# Usage:
# ./qccc <searched-command>
#

DB_FILENAME=cli-call-collection.txt
DB="$(dirname "$(readlink "$0")")/$DB_FILENAME"

if [ ! -f "$DB" ]; then
    DB="$(dirname "$0")/$DB_FILENAME"
fi

if [ ! -z "$1" ]; then
    grep -i $1 --color=auto $DB
fi
