#!/bin/bash
# Query the cli call collcetion
#
# Usage:
# ./qccc <searched-command>
#

DB_FILENAME=cli-call-collection.txt
DB="$(dirname "$(readlink "$0")")/$DB_FILENAME"
QUERY=$1
ARGV="${@:2}"

function usage {
	echo ""
	echo "Usage:    qccc <query-string> [additional grep arguments]"
	echo "Example:  qccc kerberoast -A1"
}

if [ ! -f "$DB" ]; then
    DB="$(dirname "$0")/$DB_FILENAME"
fi

if [ ! -z "$QUERY" ]; then
    grep -s -i "$QUERY" --color=auto $DB $ARGV | echo "# No results found or invalid query"
else
	usage
fi



